version: '3'

services:
  app:
    image: alpine
    command: sh -c "apk add --no-cache curl && while true; do curl -s primary-db:3306 || curl -s replica-db:3306; sleep 5; done"
    networks:
      app_net:

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      app_net:
        aliases:
          - primary-db
          - replica-db

networks:
  app_net: